Feat:  ifnpress page
Fidesnoella/ifnpress pull request #1
Opened 2023-04-22 13:02 UTC by Fidesnoella

2023-05-08 09:39 UTC, Yvad60 commented on index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
Some of these links look repeated, are all of them supposed to be there?

2023-05-08 09:39 UTC, Yvad60 commented on src/main.jsx
> +})
To separate your redux logic from the main component I would suggest moving the store to a separate file and export it to be used in the main component instead.

This will also clean the reducers imports (like publisherReducer, searchReducer)  from this component as they are not directly being used in this component

2023-05-08 09:39 UTC, Yvad60 commented on src/search.jsx
> +    }
It looks like you are rendering a loader when the status is `failed` I assume that's when there is an error. I would recommend using handle the error somehow and maybe displaying the error message for a better user experience. But I think the current approach is fine as the app will not break at least

2023-05-17 18:10 UTC, Yvad60 requested changes
Good job on these changes Miss Noella, I have some suggestion about few things you can improve on the current codebase

2023-05-17 18:10 UTC, Yvad60 commented on src/articles.jsx
> +    }, [])
When you return something inside the `useEffect` hook it will be used as the cleanup function for that Effect
I am not sure if it's it the behaviour you are going for here, but if you want to just navigate to the homepage when there there is no article I would recommend to just navigate without returning 

In that case, you can also make this into a single line like 
```js
    useEffect(() => {
        if (!article?.title) navigate("/")
    }, [])
```

2023-05-17 18:10 UTC, Yvad60 commented on src/features/search.js
> +    );
I don't think it is a good practice to just have your api key hardcoded in the codebase, I would prefer to to have it in as an environment variable in the `dotenv`. This can also be helpful because you would not have to edit your code if for instance your api key is expired and you have to change it.

2023-05-17 18:10 UTC, Yvad60 commented on package.json
> +    "dotenv": "^16.0.3",
Are you using the `dotenv` dependency?

2023-05-17 18:10 UTC, Yvad60 commented on src/features/news.js
> +    return response.data.articles;
Why are you returning after waiting another two seconds?

2023-05-17 18:10 UTC, Yvad60 commented on src/components/layout/Navbar.jsx
> +                                </div>}
I think it would be better to have the `onKeyDown` event to the actual input the user will be typing in instead of putting it on a `div` element

with the current implemenation I thinks someone by abusing the `tab` key on the keyboard they can even trigger that event without typing anything and this would make the app behave unexpectedly

2023-05-24 15:41 UTC, Yvad60 approved these changes
Looks good me now. Good job  @Fidesnoella

2023-05-25 13:23 UTC, NNesta requested changes
Good job so far but you can work on those few requested changes for the best.

2023-05-25 13:23 UTC, NNesta commented on src/loaders/TopLoader.jsx
> +export default function TopLoader({ articleorder }) {
Rename articleorder variable using camel case convention

2023-05-25 13:23 UTC, NNesta commented on src/articles.jsx
> +            <Link to={"/"} className="w-fit flex items-center gap-2 text-[#6bc5e9] font-medium text-lg hover:underline mx-3 sm:mx-0"><FaArrowLeft />Back to home</Link>
There is no need for {"/"} you can use "/" as to accept also strings

2023-05-25 13:23 UTC, NNesta commented on src/authors.jsx
> +            <Link to={"/"} className="w-fit flex items-center mx-3 sm:mx-0 gap-2 text-[#6bc5e9] font-medium text-lg hover:underline"><FaArrowLeft />Back to home</Link>
Here also There is no need for {"/"} you can use "/" as to accept also strings

2023-05-25 13:23 UTC, NNesta commented on src/components/layout/Navbar.jsx
> +                        <img src={logo} alt="IFN Press" className="h-12 xss:h-16 cursor-pointer" />
remove those bracket in to properties of Link

2023-05-25 13:23 UTC, NNesta commented on src/components/layout/Navbar.jsx
> +                                <li key={index}
Put this array in separate file and import them in here for reusability

2023-05-25 13:23 UTC, NNesta commented on src/components/layout/PageLayout.jsx
> +            {id ? null : <Top />}
no need for this ternary operator you can use && instead

2023-05-25 13:23 UTC, NNesta requested changes
Good job so far but you can work on those few requested changes for the best.

2023-05-25 14:35 UTC, NNesta approved these changes
Good job @Fidesnoella

2023-06-06 09:12 UTC, merged